### PR TITLE
mark that return type will change, for compatibility with php7

### PR DESCRIPTION
**Pull request by monomelodies**

### CODE REVIEW

**Comment by pgraham** [comment]
Dang, have not looked a this project or PHP even in years. Are you able to explain a little bit about what this change does and what problem it addresses?

**Comment by monomelodies** [comment]
Ghe, I know that feeling - only stumbled into this 'cause I had to return to an older project for the first time in... forever.

PHP8 is picky when extending classes. E.g., in class A with method foo() : string an extending class B with method foo() (no return type hint) is illegal. One should either add a return type (which is not always possible since PHP8 also introduces new virtual types like "mixed") OR add an "annotation" - in this case the built-in ReturnTypeWillChange, which signals to the engine that this is okay.

The irony here is that the new annotation feature basically aims to do what your library mimicks using doccomments. I still think it can be very useful though for other custom metadata, e.g. one could add @todo comments where necessary and run a script generating a todolist for a project. This is not possible with pure PHP annotations (as you would have to create an annotation class for every todo point, which is obviously nonsense).

Since the feature is styled as valid PHP comments, it is safe to add annotations in projects that also target <8 versions - they will simply be ignored (that IS a good thing about annotations!).

**Comment by monomelodies** [comment]
Sorry, I call them annotations, the official PHP name is "attributes". They like to keep it confusing...

**Comment by pgraham** [comment]
cool makes sense, and the change looks simple enough.

**Comment by pgraham** [comment]
This change should be available in v1.2.0 on Packgist.

**Pull request merged**
